# common(dev, prod)
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    multiple-result-sets-enabled: true
    default-statement-timeout: 3000

server:
  port: 8080
  shutdown: graceful

# secret: base64 encoding value
jwt:
  header: Authorization
  secret: ZG5JWFRBRzB2bXFzam5OX0lXVUxGTk1xcW40RFZHZEtMQUFmQ0dEVlhjVkpLOHdBSlV4bXRsbzNTd0MzZWlDaQo=
  token-validity-in-seconds: 1800

logging:
  config: classpath:log4j2.xml

regex:
  email: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamsagocorp@gmail.com
    password: cragflqpsvrmauyo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  lifecycle:
    timeout-per-shutdown-phase: 100s

  profiles:
    active: dev

---
# dev setting
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: devDB

  redis:
    host: localhost
    port: 6379

#app:
#  datasource:
#    mysql:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://localhost:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      username: root
#      password: devDB
#
#    h2:
#      jdbc-url: jdbc:h2:mem:mydb
#      username: sa
#      password: password
#      driverClassName: org.h2.Driver

---
# prod setting
spring:
  config:
    activate:
      on-profile: prod

  redis:
    master:
      host: server.sagogaja.com
      port: 6379

app:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://server.sagogaja.com:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password:
