# common(dev, prod)
server:
  port: 8080
  shutdown: graceful

# secret: base64 encoding value
jwt:
  header: Authorization
  secret: ZG5JWFRBRzB2bXFzam5OX0lXVUxGTk1xcW40RFZHZEtMQUFmQ0dEVlhjVkpLOHdBSlV4bXRsbzNTd0MzZWlDaQo=
  token-validity-in-seconds: 1800

logging:
  config: classpath:log4j2.xml

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamsagocorp@gmail.com
    password: cragflqpsvrmauyo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

  lifecycle:
    timeout-per-shutdown-phase: 100s

  devtools:
    livereload:
      enabled: true

  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

  batch:
    jdbc:
      initialize-schema: always

  profiles:
    active: dev

---
# dev setting
spring:
  config:
    activate:
      on-profile: dev

  redis:
    host: localhost
    port: 6379

app:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password: devDB

    h2:
      jdbc-url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver

---
# prod setting
spring:
  config:
    activate:
      on-profile: prod

  redis:
    master:
      host: server.sagogaja.com
      port: 6379

app:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://server.sagogaja.com:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: root
      password:
