# common(dev, prod)
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    multiple-result-sets-enabled: true
    default-statement-timeout: 3000

server:
  port: 8080

spring:
  profiles:
    active: dev

---
# dev setting
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dahyeannelee
    password: root

  redis:
    host: localhost
    port: 6379

---
# prod setting
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://server.sagogaja.com:3306/sago?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:

  redis:
    host: server.sagogaja.com
    port: 6379